### ISSUE TITLE
SIGSEGV when running v0.5.0 on Kubernetes 1.27.2

### ISSUE THREAD

**Issue by anthonysterling** [cert-manager/trust-manager#153]
👋 Hello there.

We're currently trying to deploy trust-manager v0.5.0, via the Helm chart, to a Kubernete 1.27.2 cluster and running in to a SIGSEGV from the `trust-manager ` deployment.

It's worth noting that we have a few 1.24.* clusters running v0.5.0 of trust manager just fine.

If I understand the client-go [versioning](https://github.com/kubernetes/client-go#versioning) correctly, this project is [consuming v0.27.2](https://github.com/cert-manager/trust-manager/blob/3ad9f293f59ccd15765fccfe6623bef6192cc79e/go.mod#L16) so it should be 1.27.2 compatible. 🤔 

Thanks for any/all pointers towards a solution here. 🙇‍♂️ 

##### sigsegv.txt 👇 
<details>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c55d0]
goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc000147e18, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0001460f0, 0x15}, {0xc0003e05c0, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x18da633?)
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:310 +0x47c
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc00013aaa0?)
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:198 +0x5c
k8s.io/client-go/discovery.ServerGroupsAndResources({0x1b6cd28, 0xc000133200})
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:392 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:356 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc0000e6e90)
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:621 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x203000?)
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:355 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x1b6cd28?, 0xc000133200?})
	/go/pkg/mod/k8s.io/client-go@v0.26.1/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:86 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:119
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc00013cd80?, {0x0, 0x0, 0x1?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:99 +0x176
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0xc0000c0770?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc0003ee000, {0xc0004ad818, 0x1, 0x1b69148?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0xc0000c0770, 0x0, 0x0, {{0x1b69148, 0xc000401e00}, 0x0}, 0x1, {0x0, 0x0}, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/manager/manager.go:351 +0xf9
github.com/cert-manager/trust-manager/cmd/trust-manager/app.NewCommand.func1(0xc00007e000?, {0x18db28d?, 0x9?, 0x9?})
	/workspace/cmd/trust-manager/app/app.go:67 +0x479
github.com/spf13/cobra.(*Command).execute(0xc00007e000, {0xc000124010, 0x9, 0x9})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00007e000)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/workspace/cmd/trust-manager/main.go:29 +0x1e
```
</details>

**Comment by anthonysterling** [comment]
Oh hey, me again. 😆 

Almost as soon as I pressed "Submit" I thought it was worth checking of the vendor updates were included in the v0.5.0 release, and 🤦‍♂️, nope, they're not which explains why it's not yet compatible with 1.27.2.

I have manually built and deployment this from `master` and we're no longer SIGSEGV'ing.

I'll close this out and await the next release, thanks!
